
farm.fd2_%ENTRY_POINT%.content:
  path: '/fd2/%ENTRY_POINT%'
  defaults:
    _controller: '\Drupal\farm_fd2\Controller\FD2_Controller::content'
    _title: '%ENTRY_POINT_TITLE%'
  requirements:
    _permission: 'access content'