# Github action that runs the lint-changed script for this repo.
# This script will:
#   - Performs lint / spell / link checks
#   - Format files
#   - Runs all tests on any changed entrypoints, components, or library files.
#   - Runs any changed tests.
#
# Note some tests may run twice (e.g. if a .vue and .cy.js are both changed).

name: Pull Request Preflight

on:
  pull_request_target:
    branches:
      - main

#permissions:
#  contents: read, write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  pr-preflight:
    name: Check linting, spelling & formatting and run tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out the git repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install npm dependencies
        run: npm ci

      - name: Install shfmt shell formatter
        run: curl -sS https://webinstall.dev/shfmt | bash

      - name: Run lint-staged
        run: npx lint-staged \
          --config .lintstagedrc.cjs \
          --concurrent false \
          --diff="${{ github.base_ref }}...${{ github.head_ref }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
