# Github action that runs on PR's to main.
# Performs lint / spell / link checks
# Runs smoke tests

name: FD2 PR Preflight

on: 
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main

permissions:
  contents: read

jobs:
  pr-pre-flight:
    name: Pull request preflight
    runs-on: ubuntu-latest

    steps:
      - name: Check out git repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci

      - name: Identify changed files
        id: changed-files
        uses: tj-actions/changed-files@v37

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done

#      - name: Run step if test file(s) change
#        if: steps.changed-files.outputs.test_any_changed == 'true'
#        run: |
#          echo "One or more test file(s) has changed."
#          echo "List all the files that have changed: ${{ steps.changed-files.outputs.all_changed_files }}"
      


